//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMeDraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionReport
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public int ReporterID { get; set; }
        public Nullable<int> ReportHandlerID { get; set; }
        public string Reason { get; set; }
        public System.DateTime ReportDatetime { get; set; }
        public bool Status { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
